# Generated by Django 4.0.5 on 2022-06-18 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio_library', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='title',
            new_name='name',
        ),
    ]
